on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Action test
    steps:
      - uses: m-mizutani/cs-alert-notify@4a8908c980e48882bb7b5e6bd98dc05b313f26b7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
