on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Action test
    steps:
      - uses: m-mizutani/cs-alert-notify@dfdc18a9c9e3baa735f072f1688bad5c933a204a
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
