name: Vuln scan

on:
  pull_request:
    types: ["opened", "synchronize"]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout upstream repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
      - run: cat trivy-results.sarif
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "trivy-results.sarif"
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.head_ref != '' }}
    needs: scan
    steps:
      - uses: m-mizutani/code-scanning-notify@29d7f2316b42072ca06ffd1128437a35112c9fa4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{ github.head_ref }}
          base-ref: ${{ github.base_ref }}
          repo: ${{ github.repository }}
          issue-id: github.event.number
